-- Release repair enums. ADD VALUE cannot share a transaction with first use on some PG versions.

ALTER TYPE run_type ADD VALUE IF NOT EXISTS 'DETERMINISTIC_SUITE';
ALTER TYPE run_type ADD VALUE IF NOT EXISTS 'LIVE_COMPATIBILITY_SUITE';
ALTER TYPE run_type ADD VALUE IF NOT EXISTS 'LIVE_COMMERCIAL_SUITE';
ALTER TYPE run_type ADD VALUE IF NOT EXISTS 'LIVE_SESSION';
ALTER TYPE run_type ADD VALUE IF NOT EXISTS 'EVALUATION_SITTING';
ALTER TYPE run_state ADD VALUE IF NOT EXISTS 'PARTIAL';

INSERT INTO schema_migrations (version)
VALUES ('0005_release_enums')
ON CONFLICT (version) DO NOTHING;
